# Generated by Django 5.0.7 on 2024-07-20 16:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Autor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=30, verbose_name='Nombre del autor')),
                ('Apellido', models.CharField(max_length=30, verbose_name='Apellido del autor')),
            ],
            options={
                'db_table': 'autores',
            },
        ),
        migrations.CreateModel(
            name='Obra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Titulo', models.CharField(max_length=50, verbose_name='Titulo de la Obra')),
                ('Fecha_Exposicion', models.DateField()),
                ('Autor', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='myapp.autor')),
            ],
            options={
                'db_table': 'obras',
            },
        ),
    ]
