# Generated by Django 5.0.7 on 2024-07-20 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_autor_pintura'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autor',
            name='Pintura',
            field=models.CharField(max_length=50, verbose_name='Estilo de pintura'),
        ),
    ]
